server:
  port: 9070

logging:
  level:
    "[org.springframework.security]": TRACE

spring:
  output:
    ansi:
      enabled: always
  application:
    name: cropzilla
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: cropzilla-client
            client-secret: XyhE9Xh1wP1SGcwMS3xWQYxBALrBSGk7
            scope: openid,profile,email
            redirect-uri: http://localhost:9070/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/cropzilla-realm
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/cropzilla-realm/protocol/openid-connect/certs
